// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $edited } from "./$edited.js";
import { $hasEditable } from "./$hasEditable.js";
import { $hasEdited } from "./$hasEdited.js";
import { $isSaving } from "./$isSaving.js";
import { $showSavingDone } from "./$showSavingDone.js";
import { $showSavingSpinner } from "./$showSavingSpinner.js";
import { $tracks } from "./$tracks.js";
import { empty } from "./empty.js";
import { forTrack } from "./forTrack.js";
import { forTracks } from "./forTracks.js";

type Tags = {
    album: string
    artist: string
    diskNr?: number
    title: string
    trackNr?: number
    year?: number
}

type EditableTags = {
    [K in keyof Tags]-?: string
}

declare namespace Tags {
    export {
        $edited,
        $hasEditable,
        $hasEdited,
        $isSaving,
        $showSavingDone,
        $showSavingSpinner,
        $tracks,
        empty,
        forTrack,
        forTracks,
    }
}

export {
    Tags,
    EditableTags,
}
