// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $edited } from "./$edited.js";
import { $hasEditable } from "./$hasEditable.js";
import { $hasEdited } from "./$hasEdited.js";
import { $isSaving } from "./$isSaving.js";
import { $showSavingDone } from "./$showSavingDone.js";
import { $showSavingSpinner } from "./$showSavingSpinner.js";
import { $tracks } from "./$tracks.js";
import { empty } from "./empty.js";
import { forTrack } from "./forTrack.js";
import { forTracks } from "./forTracks.js";

export const Tags = {
    $edited,
    $hasEditable,
    $hasEdited,
    $isSaving,
    $showSavingDone,
    $showSavingSpinner,
    $tracks,
    empty,
    forTrack,
    forTracks,
}
