// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $accent } from "./$accent.js";
import { $darkName } from "./$darkName.js";
import { $lightName } from "./$lightName.js";
import { $mode } from "./$mode.js";
import { $name } from "./$name.js";
import { $waveform } from "./$waveform.js";
import { $waveformName } from "./$waveformName.js";
import { $waveformProgressColor } from "./$waveformProgressColor.js";
import { $waveformWaveColor } from "./$waveformWaveColor.js";

export const Theme = {
    $accent,
    $darkName,
    $lightName,
    $mode,
    $name,
    $waveform,
    $waveformName,
    $waveformProgressColor,
    $waveformWaveColor,
}
