// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $audioDir } from "./$audioDir.js";
import { $dataDir } from "./$dataDir.js";
import { $homeDir } from "./$homeDir.js";
import { $libraryDir } from "./$libraryDir.js";
import { moveFiles } from "./moveFiles.js";
import { readJSON } from "./readJSON.js";
import { readText } from "./readText.js";
import { removeFiles } from "./removeFiles.js";
import { scanFiles } from "./scanFiles.js";
import { trashFiles } from "./trashFiles.js";
import { writeJSON } from "./writeJSON.js";

export const Fs = {
    $audioDir,
    $dataDir,
    $homeDir,
    $libraryDir,
    moveFiles,
    readJSON,
    readText,
    removeFiles,
    scanFiles,
    trashFiles,
    writeJSON,
}
