// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $activeTab } from "./$activeTab.js";
import { $isOpen } from "./$isOpen.js";
import { $isToggling } from "./$isToggling.js";
import { $isVisible } from "./$isVisible.js";
import { $playlistDetails } from "./$playlistDetails.js";
import { $trackDetails } from "./$trackDetails.js";

export const Sidepanel = {
    $activeTab,
    $isOpen,
    $isToggling,
    $isVisible,
    $playlistDetails,
    $trackDetails,
}
