// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $activeTab } from "./$activeTab.js";
import { $isOpen } from "./$isOpen.js";
import { $isToggling } from "./$isToggling.js";
import { $isVisible } from "./$isVisible.js";
import { $playlistDetails } from "./$playlistDetails.js";
import { $trackDetails } from "./$trackDetails.js";
import { PlaylistDetails } from "./types.js";
import { TrackDetails } from "./types.js";

declare namespace Sidepanel {
    export {
        $activeTab,
        $isOpen,
        $isToggling,
        $isVisible,
        $playlistDetails,
        $trackDetails,
    }
}

export {
    Sidepanel,
    PlaylistDetails,
    TrackDetails,
}
