// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $hasNext } from "./$hasNext.js";
import { $hasPrev } from "./$hasPrev.js";
import { $nextIds } from "./$nextIds.js";
import { $nextQueue } from "./$nextQueue.js";
import { $prevIds } from "./$prevIds.js";
import { $prevQueue } from "./$prevQueue.js";

export const TrackHistory = {
    $hasNext,
    $hasPrev,
    $nextIds,
    $nextQueue,
    $prevIds,
    $prevQueue,
}
