// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $tree } from "./$tree.js";
import { children } from "./children.js";
import { collect } from "./collect.js";
import { collectIds } from "./collectIds.js";
import { create } from "./create.js";
import { depth } from "./depth.js";
import { hasChildren } from "./hasChildren.js";
import { parentIds } from "./parentIds.js";
import { parents } from "./parents.js";

export const PlaylistTree = {
    $tree,
    children,
    collect,
    collectIds,
    create,
    depth,
    hasChildren,
    parentIds,
    parents,
}
