// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $tree } from "./$tree.js";
import { children } from "./children.js";
import { collect } from "./collect.js";
import { collectIds } from "./collectIds.js";
import { create } from "./create.js";
import { depth } from "./depth.js";
import { hasChildren } from "./hasChildren.js";
import { parentIds } from "./parentIds.js";
import { parents } from "./parents.js";
import { Playlist } from "../Playlists/index.js";

type PlaylistTree = {
    children: PlaylistTreeNode[]
    nodes: Map<string, PlaylistTreeNode>
}

type PlaylistTreeNode = {
    children: PlaylistTreeNode[]
    depth: number
    parent?: PlaylistTreeNode
    playlist: Playlist
}

declare namespace PlaylistTree {
    export {
        $tree,
        children,
        collect,
        collectIds,
        create,
        depth,
        hasChildren,
        parentIds,
        parents,
    }
}

export {
    PlaylistTree,
    PlaylistTreeNode,
}
