// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $canPlay } from "./$canPlay.js";
import { $duration } from "./$duration.js";
import { $hasTrack } from "./$hasTrack.js";
import { $isPlaying } from "./$isPlaying.js";
import { $mode } from "./$mode.js";
import { $peaks } from "./$peaks.js";
import { $position } from "./$position.js";
import { $track } from "./$track.js";
import { $trackId } from "./$trackId.js";
import { $trackIds } from "./$trackIds.js";
import { $tracks } from "./$tracks.js";
import { $volume } from "./$volume.js";
import { $wavesurfer } from "./$wavesurfer.js";
import { Mode } from "./types.js";

declare namespace Playback {
    export {
        $canPlay,
        $duration,
        $hasTrack,
        $isPlaying,
        $mode,
        $peaks,
        $position,
        $track,
        $trackId,
        $trackIds,
        $tracks,
        $volume,
        $wavesurfer,
    }
}

export {
    Playback,
    Mode,
}
