// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $config } from "./$config.js";
import { Mode } from "../Playback/index.js";
import { ThemeMode } from "../Theme/index.js";
import { ThemeNameDark } from "../Theme/index.js";
import { ThemeNameLight } from "../Theme/index.js";
import { WaveformThemeName } from "../Theme/index.js";

type Config = {
    darkThemeName?: ThemeNameDark
    lightThemeName?: ThemeNameLight
    mode?: Mode
    sidebarWidth?: number
    themeMode?: ThemeMode
    waveformTheme?: WaveformThemeName
}

declare namespace Config {
    export {
        $config,
    }
}

export {
    Config,
}
