// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $config } from "./$config.js";

export const Config = {
    $config,
}
