// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { clearSelection } from "./clearSelection.js";
import { collapseSelection } from "./collapseSelection.js";
import { createLSM } from "./createLSM.js";
import { getLastSelection } from "./getLastSelection.js";
import { getLastSelectionPosition } from "./getLastSelectionPosition.js";
import { getNthSelection } from "./getNthSelection.js";
import { getSelectable } from "./getSelectable.js";
import { getSelectionPosition } from "./getSelectionPosition.js";
import { getSelections } from "./getSelections.js";
import { goToBottom } from "./goToBottom.js";
import { goToNext } from "./goToNext.js";
import { goToPrev } from "./goToPrev.js";
import { goToTop } from "./goToTop.js";
import { handleMouseEvent } from "./handleMouseEvent.js";
import { hasMultipleSelections } from "./hasMultipleSelections.js";
import { hasNoSelection } from "./hasNoSelection.js";
import { hasSelection } from "./hasSelection.js";
import { hasSingleSelection } from "./hasSingleSelection.js";
import { isFirstSelection } from "./isFirstSelection.js";
import { isFirstSelectionInGroup } from "./isFirstSelectionInGroup.js";
import { isLastSelection } from "./isLastSelection.js";
import { isLastSelectionInGroup } from "./isLastSelectionInGroup.js";
import { isSelected } from "./isSelected.js";
import { select } from "./select.js";
import { selectAll } from "./selectAll.js";
import { selectNext } from "./selectNext.js";
import { selectOne } from "./selectOne.js";
import { selectPosition } from "./selectPosition.js";
import { selectPrev } from "./selectPrev.js";
import { selectTo } from "./selectTo.js";
import { selectToBottom } from "./selectToBottom.js";
import { selectToTop } from "./selectToTop.js";
import { setSelectables } from "./setSelectables.js";
import { toggleSelect } from "./toggleSelect.js";
import { unselect } from "./unselect.js";

export const LSM = {
    clearSelection,
    collapseSelection,
    createLSM,
    getLastSelection,
    getLastSelectionPosition,
    getNthSelection,
    getSelectable,
    getSelectionPosition,
    getSelections,
    goToBottom,
    goToNext,
    goToPrev,
    goToTop,
    handleMouseEvent,
    hasMultipleSelections,
    hasNoSelection,
    hasSelection,
    hasSingleSelection,
    isFirstSelection,
    isFirstSelectionInGroup,
    isLastSelection,
    isLastSelectionInGroup,
    isSelected,
    select,
    selectAll,
    selectNext,
    selectOne,
    selectPosition,
    selectPrev,
    selectTo,
    selectToBottom,
    selectToTop,
    setSelectables,
    toggleSelect,
    unselect,
}
