export const shortcuts = {
    showCmdMenu: ['cmd+k', 'cmd+p', 'cmd+shift+k', 'cmd+shift+p'],
    createPlaylist: ['cmd+n'],
    syncLibrary: ['cmd+s'],
    toggleMute: ['cmd+m'],
    setRepeatMode: ['cmd+r'],
    toggleMode: ['cmd+r'],
    togglePlayback: ['space'],
    switchFocus: ['tab'],
    focusSearchInput: ['cmd+f'],
    goToPrev: ['up'],
    goToNext: ['down'],
    selectPrev: ['shift+up'],
    selectNext: ['shift+down'],
    selectAll: ['cmd+a'],
    goToTop: ['cmd+up'],
    goToBottom: ['cmd+down'],
    selectToTop: ['cmd+shift+up'],
    selectToBottom: ['cmd+shift+down'],
    setVolume10: ['cmd+1'],
    setVolume20: ['cmd+2'],
    setVolume30: ['cmd+3'],
    setVolume40: ['cmd+4'],
    setVolume50: ['cmd+5'],
    setVolume60: ['cmd+6'],
    setVolume70: ['cmd+7'],
    setVolume80: ['cmd+8'],
    setVolume90: ['cmd+9'],
    setVolume100: ['cmd+0'],
}
