export const shortcuts = {
    createPlaylist: ["cmd+n", "ctrl+n"],
    focusSearchInput: ["/", "cmd+f", "ctrl+f"],
    goToBottom: ["cmd+down", "ctrl+down", "G"],
    goToNext: ["down", "j"],
    goToPrev: ["up", "k"],
    goToTop: ["cmd+up", "ctrl+up", "g"],
    importTracks: ["i"],
    playNext: ["right", ">"],
    playPrev: ["left", "<"],
    playSelected: ["enter"],
    reload: ["cmd+shift+r", "ctrl+shift+r"],
    seekBackward: ["b"],
    seekForward: ["f"],
    selectAll: ["cmd+a", "ctrl+a"],
    selectNext: ["shift+down"],
    selectPrev: ["shift+up"],
    selectToBottom: ["cmd+shift+down", "ctrl+shift+down"],
    selectToTop: ["cmd+shift+up", "ctrl+shift+up"],
    setVolume10: ["1"],
    setVolume20: ["2"],
    setVolume30: ["3"],
    setVolume40: ["4"],
    setVolume50: ["5"],
    setVolume60: ["6"],
    setVolume70: ["7"],
    setVolume80: ["8"],
    setVolume90: ["9"],
    setVolume100: ["0"],
    showCmdMenu: ["cmd+k", "cmd+p", "cmd+shift+k", "cmd+shift+p", "ctrl+k", "ctrl+p", "ctrl+shift+k", "ctrl+shift+p"],
    switchFocus: ["tab"],
    syncLibrary: ["u"],
    toggleMode: ["r", "v", "x"],
    toggleMute: ["m"],
    togglePlayback: ["space", "p"],
}
