// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { CommandMenu } from "./CommandMenu.js";
import { createContextMenu } from "./createContextMenu.js";
import { createPopover } from "./createPopover.js";
import { createTooltip } from "./createTooltip.js";

export const Modals = {
    CommandMenu,
    createContextMenu,
    createPopover,
    createTooltip,
}
