// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $all } from "./$all.js";
import { $byFilehash } from "./$byFilehash.js";
import { $byId } from "./$byId.js";
import { $unsortedCount } from "./$unsortedCount.js";
import { $unsortedIds } from "./$unsortedIds.js";
import { albumTracksComparator } from "./sort.js";
import { filter } from "./filter.js";
import { forLibrary } from "./forLibrary.js";
import { format } from "./format.js";
import { formatDuration } from "./formatDuration.js";
import { forPlaylist } from "./forPlaylist.js";
import { forRecentlyAdded } from "./forRecentlyAdded.js";
import { forUnsorted } from "./forUnsorted.js";
import { sort } from "./sort.js";
import { updateMetadata } from "./updateMetadata.js";
import { upsert } from "./upsert.js";

export const Tracks = {
    $all,
    $byFilehash,
    $byId,
    $unsortedCount,
    $unsortedIds,
    albumTracksComparator,
    filter,
    forLibrary,
    format,
    formatDuration,
    forPlaylist,
    forRecentlyAdded,
    forUnsorted,
    sort,
    updateMetadata,
    upsert,
}
